import * as stylex from '@stylexjs/stylex';
import { colors } from '../../tokens/colors.stylex';
import { spacing } from '../../tokens/spacing.stylex';
import { borders } from '../../tokens/borders.stylex';
import { shape } from '../../tokens/shape.stylex';
import { elevation } from '../../tokens/elevation.stylex';
import { fonts, fontSizes, fontWeights, lineHeights } from '../../tokens/typography.stylex';
import { durations, easings } from '../../tokens/motion.stylex';

const fadeIn = stylex.keyframes({
  from: { opacity: 0, transform: 'translateY(-4px)' },
  to: { opacity: 1, transform: 'translateY(0)' },
});

export const styles = stylex.create({
  root: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.space1,
    width: '100%',
  },
  labelContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.space1,
  },
  label: {
    fontFamily: fonts.sans,
    fontSize: fontSizes.bodyMd,
    lineHeight: lineHeights.bodyMd,
    fontWeight: fontWeights.medium,
    color: colors.textStrong,
  },
  requiredAsterisk: {
    color: colors.textError,
  },
  hint: {
    fontFamily: fonts.sans,
    fontSize: fontSizes.bodyMd,
    lineHeight: lineHeights.bodyMd,
    fontWeight: fontWeights.regular,
    color: colors.textWeak,
  },
  errorContainer: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: spacing.space1,
    color: colors.textError,
  },
  errorIcon: {
    flexShrink: 0,
    marginTop: spacing.space05,
  },
  errorText: {
    fontFamily: fonts.sans,
    fontSize: fontSizes.bodyMd,
    lineHeight: lineHeights.bodyMd,
    fontWeight: fontWeights.regular,
    color: colors.textError,
  },
  trigger: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    fontFamily: fonts.sans,
    fontSize: fontSizes.bodyMd,
    lineHeight: lineHeights.bodyMd,
    color: colors.textStrong,
    backgroundColor: {
      default: colors.backgroundBase,
      ':hover': colors.fillWeak,
      ':active': colors.fillPress,
    },
    borderWidth: borders.hairline,
    borderStyle: 'solid',
    borderColor: {
      default: colors.strokeStrong,
      ':hover': colors.strokeStrong,
    },
    borderRadius: shape.radiusMd,
    paddingTop: spacing.space2,
    paddingBottom: spacing.space2,
    paddingLeft: spacing.space3,
    paddingRight: spacing.space3,
    outline: 'none',
    transitionProperty: 'border-color, background-color, color, box-shadow',
    transitionDuration: durations.fast,
    transitionTimingFunction: easings.standard,
    cursor: 'pointer',
    textAlign: 'left',
    ':focus': {
      outlineWidth: borders.medium,
      outlineStyle: 'solid',
      outlineColor: colors.focus,
      outlineOffset: spacing.space05,
      borderColor: colors.strokeFocus,
    },
  },
  triggerPlaceholder: {
    color: colors.textWeak,
  },
  triggerInvalid: {
    borderColor: colors.strokeErrorStrong,
    backgroundColor: colors.fillErrorWeak,
    ':focus': {
      borderColor: colors.strokeErrorStrong,
      outlineWidth: borders.medium,
      outlineStyle: 'solid',
      outlineColor: colors.textError,
      outlineOffset: spacing.space05,
    },
  },
  triggerDisabled: {
    opacity: 0.5,
    pointerEvents: 'none',
    backgroundColor: colors.fillDisabled,
    borderColor: colors.strokeDisabled,
  },
  icon: {
    color: colors.textWeak,
    flexShrink: 0,
    marginLeft: spacing.space2,
  },
  popoverContent: {
    backgroundColor: colors.backgroundRaised,
    borderRadius: shape.radiusMd,
    borderWidth: borders.hairline,
    borderStyle: 'solid',
    borderColor: colors.strokeWeak,
    boxShadow: elevation.elev3,
    padding: spacing.space3,
    animationName: fadeIn,
    animationDuration: durations.fast,
    animationTimingFunction: easings.standard,
    zIndex: 50,
  },
  // react-day-picker styles mapping
  rdpRoot: {
    fontFamily: fonts.sans,
    position: 'relative',
    color: colors.textStrong,
  },
  rdpMonths: {
    display: 'flex',
    flexDirection: 'column',
  },
  rdpMonth: {
    display: 'flex',
    flexDirection: 'column',
    gap: spacing.space3,
    position: 'relative',
  },
  rdpCaption: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    height: spacing.space8,
  },
  rdpCaptionLabel: {
    fontSize: fontSizes.bodyMd,
    fontWeight: fontWeights.semiBold,
    color: colors.textStrong,
  },
  rdpNav: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'absolute',
    width: '100%',
    height: spacing.space8,
    pointerEvents: 'none',
    top: 0,
    left: 0,
    zIndex: 10,
  },
  rdpNavButton: {
    all: 'unset',
    borderWidth: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: spacing.space8,
    height: spacing.space8,
    borderRadius: shape.radiusSm,
    color: colors.textStrong,
    cursor: 'pointer',
    pointerEvents: 'auto',
    backgroundColor: {
      default: 'transparent',
      ':hover': colors.fillWeak,
    },
    transitionProperty: 'background-color, color',
    transitionDuration: durations.fast,
    transitionTimingFunction: easings.standard,
  },
  rdpNavButtonPrevious: {},
  rdpNavButtonNext: {},
  rdpHead: {
    marginBottom: spacing.space2,
  },
  rdpHeadRow: {},
  rdpHeadCell: {
    color: colors.textWeak,
    fontSize: fontSizes.bodySm,
    fontWeight: fontWeights.medium,
    width: spacing.space8,
    height: spacing.space8,
    textAlign: 'center',
    verticalAlign: 'middle',
    padding: 0,
  },
  rdpTbody: {},
  rdpRow: {},
  rdpCell: {
    position: 'relative',
    padding: 0,
    textAlign: 'center',
    verticalAlign: 'middle',
  },
  rdpDay: {
    all: 'unset',
    borderWidth: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: spacing.space8,
    height: spacing.space8,
    borderRadius: shape.radiusSm,
    fontSize: fontSizes.bodySm,
    color: colors.textStrong,
    cursor: 'pointer',
    backgroundColor: {
      default: 'transparent',
      ':hover': colors.fillWeak,
    },
    transitionProperty: 'background-color, color',
    transitionDuration: durations.fast,
    transitionTimingFunction: easings.standard,
  },
  rdpDaySelected: {
    backgroundColor: {
      default: colors.fillBrandStrong,
      ':hover': colors.fillBrandStrong,
    },
    color: colors.textInverseStrong,
    fontWeight: fontWeights.medium,
    borderRadius: shape.radiusMd,
  },
  rdpDayToday: {
    fontWeight: fontWeights.semiBold,
    color: colors.textBrand,
  },
  rdpDayOutside: {
    color: colors.textWeak,
    opacity: 0.5,
  },
  rdpDayDisabled: {
    color: colors.textWeak,
    opacity: 0.3,
    pointerEvents: 'none',
  },
});
